// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: trade.proto

package tradebotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==========================
// Requests (Python → Go)
// ==========================
type TradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"` // BTCUSDT
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // BUY | SELL | HOLD
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // signal time (ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeRequest) Reset() {
	*x = TradeRequest{}
	mi := &file_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequest) ProtoMessage() {}

func (x *TradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequest.ProtoReflect.Descriptor instead.
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *TradeRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *TradeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TradeRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ==========================
// Responses (Go → Python)
// ==========================
type TradeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BotId           string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Symbol          string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // BUY | SELL
	OrderId         string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                       // FILLED | PARTIALLY_FILLED | REJECTED
	AvgPrice        float64                `protobuf:"fixed64,6,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"` // TRUE execution price
	ExecutedQty     float64                `protobuf:"fixed64,7,opt,name=executed_qty,json=executedQty,proto3" json:"executed_qty,omitempty"`
	QuoteQty        float64                `protobuf:"fixed64,8,opt,name=quote_qty,json=quoteQty,proto3" json:"quote_qty,omitempty"` // total USDT spent / received
	Commission      float64                `protobuf:"fixed64,9,opt,name=commission,proto3" json:"commission,omitempty"`
	CommissionAsset string                 `protobuf:"bytes,10,opt,name=commission_asset,json=commissionAsset,proto3" json:"commission_asset,omitempty"`
	ExecutedAt      int64                  `protobuf:"varint,11,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"` // exchange execution time (ms)
	Fills           []*Fill                `protobuf:"bytes,12,rep,name=fills,proto3" json:"fills,omitempty"`                              // raw execution truth
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{1}
}

func (x *TradeResponse) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *TradeResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradeResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TradeResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TradeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TradeResponse) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *TradeResponse) GetExecutedQty() float64 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *TradeResponse) GetQuoteQty() float64 {
	if x != nil {
		return x.QuoteQty
	}
	return 0
}

func (x *TradeResponse) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *TradeResponse) GetCommissionAsset() string {
	if x != nil {
		return x.CommissionAsset
	}
	return ""
}

func (x *TradeResponse) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

func (x *TradeResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

// ==========================
// Execution Fills
// ==========================
type Fill struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Price           float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty             float64                `protobuf:"fixed64,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Commission      float64                `protobuf:"fixed64,3,opt,name=commission,proto3" json:"commission,omitempty"`
	CommissionAsset string                 `protobuf:"bytes,4,opt,name=commission_asset,json=commissionAsset,proto3" json:"commission_asset,omitempty"`
	TradeId         int64                  `protobuf:"varint,5,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{2}
}

func (x *Fill) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Fill) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Fill) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *Fill) GetCommissionAsset() string {
	if x != nil {
		return x.CommissionAsset
	}
	return ""
}

func (x *Fill) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

var File_trade_proto protoreflect.FileDescriptor

const file_trade_proto_rawDesc = "" +
	"\n" +
	"\vtrade.proto\x12\x05trade\"\xab\x01\n" +
	"\fTradeRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xf5\x02\n" +
	"\rTradeResponse\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tavg_price\x18\x06 \x01(\x01R\bavgPrice\x12!\n" +
	"\fexecuted_qty\x18\a \x01(\x01R\vexecutedQty\x12\x1b\n" +
	"\tquote_qty\x18\b \x01(\x01R\bquoteQty\x12\x1e\n" +
	"\n" +
	"commission\x18\t \x01(\x01R\n" +
	"commission\x12)\n" +
	"\x10commission_asset\x18\n" +
	" \x01(\tR\x0fcommissionAsset\x12\x1f\n" +
	"\vexecuted_at\x18\v \x01(\x03R\n" +
	"executedAt\x12!\n" +
	"\x05fills\x18\f \x03(\v2\v.trade.FillR\x05fills\"\x94\x01\n" +
	"\x04Fill\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x01R\x03qty\x12\x1e\n" +
	"\n" +
	"commission\x18\x03 \x01(\x01R\n" +
	"commission\x12)\n" +
	"\x10commission_asset\x18\x04 \x01(\tR\x0fcommissionAsset\x12\x19\n" +
	"\btrade_id\x18\x05 \x01(\x03R\atradeId2L\n" +
	"\x0fTradeBotService\x129\n" +
	"\fExecuteTrade\x12\x13.trade.TradeRequest\x1a\x14.trade.TradeResponseB\x19Z\x17./tradebotpb;tradebotpbb\x06proto3"

var (
	file_trade_proto_rawDescOnce sync.Once
	file_trade_proto_rawDescData []byte
)

func file_trade_proto_rawDescGZIP() []byte {
	file_trade_proto_rawDescOnce.Do(func() {
		file_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)))
	})
	return file_trade_proto_rawDescData
}

var file_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trade_proto_goTypes = []any{
	(*TradeRequest)(nil),  // 0: trade.TradeRequest
	(*TradeResponse)(nil), // 1: trade.TradeResponse
	(*Fill)(nil),          // 2: trade.Fill
}
var file_trade_proto_depIdxs = []int32{
	2, // 0: trade.TradeResponse.fills:type_name -> trade.Fill
	0, // 1: trade.TradeBotService.ExecuteTrade:input_type -> trade.TradeRequest
	1, // 2: trade.TradeBotService.ExecuteTrade:output_type -> trade.TradeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trade_proto_init() }
func file_trade_proto_init() {
	if File_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_proto_goTypes,
		DependencyIndexes: file_trade_proto_depIdxs,
		MessageInfos:      file_trade_proto_msgTypes,
	}.Build()
	File_trade_proto = out.File
	file_trade_proto_goTypes = nil
	file_trade_proto_depIdxs = nil
}
