// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: gRPC/proto/trade.proto

package trade

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeBotService_TradeBotAction_FullMethodName = "/trade.TradeBotService/TradeBotAction"
)

// TradeBotServiceClient is the client API for TradeBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeBotServiceClient interface {
	TradeBotAction(ctx context.Context, in *TradeBotRequest, opts ...grpc.CallOption) (*TradeBotRequestReply, error)
}

type tradeBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeBotServiceClient(cc grpc.ClientConnInterface) TradeBotServiceClient {
	return &tradeBotServiceClient{cc}
}

func (c *tradeBotServiceClient) TradeBotAction(ctx context.Context, in *TradeBotRequest, opts ...grpc.CallOption) (*TradeBotRequestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeBotRequestReply)
	err := c.cc.Invoke(ctx, TradeBotService_TradeBotAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeBotServiceServer is the server API for TradeBotService service.
// All implementations must embed UnimplementedTradeBotServiceServer
// for forward compatibility.
type TradeBotServiceServer interface {
	TradeBotAction(context.Context, *TradeBotRequest) (*TradeBotRequestReply, error)
	mustEmbedUnimplementedTradeBotServiceServer()
}

// UnimplementedTradeBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeBotServiceServer struct{}

func (UnimplementedTradeBotServiceServer) TradeBotAction(context.Context, *TradeBotRequest) (*TradeBotRequestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeBotAction not implemented")
}
func (UnimplementedTradeBotServiceServer) mustEmbedUnimplementedTradeBotServiceServer() {}
func (UnimplementedTradeBotServiceServer) testEmbeddedByValue()                         {}

// UnsafeTradeBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeBotServiceServer will
// result in compilation errors.
type UnsafeTradeBotServiceServer interface {
	mustEmbedUnimplementedTradeBotServiceServer()
}

func RegisterTradeBotServiceServer(s grpc.ServiceRegistrar, srv TradeBotServiceServer) {
	// If the following call pancis, it indicates UnimplementedTradeBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeBotService_ServiceDesc, srv)
}

func _TradeBotService_TradeBotAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBotServiceServer).TradeBotAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBotService_TradeBotAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBotServiceServer).TradeBotAction(ctx, req.(*TradeBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeBotService_ServiceDesc is the grpc.ServiceDesc for TradeBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade.TradeBotService",
	HandlerType: (*TradeBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TradeBotAction",
			Handler:    _TradeBotService_TradeBotAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/proto/trade.proto",
}
