// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: gRPC/proto/trade.proto

package trade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ExchangePair  string                 `protobuf:"bytes,3,opt,name=exchangePair,proto3" json:"exchangePair,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Strategy      string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeBotRequest) Reset() {
	*x = TradeBotRequest{}
	mi := &file_gRPC_proto_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeBotRequest) ProtoMessage() {}

func (x *TradeBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeBotRequest.ProtoReflect.Descriptor instead.
func (*TradeBotRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeBotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *TradeBotRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TradeBotRequest) GetExchangePair() string {
	if x != nil {
		return x.ExchangePair
	}
	return ""
}

func (x *TradeBotRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TradeBotRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type TradeBotRequestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=botId,proto3" json:"botId,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,2,opt,name=clientOrderId,proto3" json:"clientOrderId,omitempty"`
	IsCompleted   bool                   `protobuf:"varint,3,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,4,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	Strategy      string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeBotRequestReply) Reset() {
	*x = TradeBotRequestReply{}
	mi := &file_gRPC_proto_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeBotRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeBotRequestReply) ProtoMessage() {}

func (x *TradeBotRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeBotRequestReply.ProtoReflect.Descriptor instead.
func (*TradeBotRequestReply) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_trade_proto_rawDescGZIP(), []int{1}
}

func (x *TradeBotRequestReply) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *TradeBotRequestReply) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *TradeBotRequestReply) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *TradeBotRequestReply) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *TradeBotRequestReply) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

var File_gRPC_proto_trade_proto protoreflect.FileDescriptor

const file_gRPC_proto_trade_proto_rawDesc = "" +
	"\n" +
	"\x16gRPC/proto/trade.proto\x12\x05trade\"\x98\x01\n" +
	"\x0fTradeBotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\"\n" +
	"\fexchangePair\x18\x03 \x01(\tR\fexchangePair\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\"\xb2\x01\n" +
	"\x14TradeBotRequestReply\x12\x14\n" +
	"\x05botId\x18\x01 \x01(\tR\x05botId\x12$\n" +
	"\rclientOrderId\x18\x02 \x01(\tR\rclientOrderId\x12 \n" +
	"\visCompleted\x18\x03 \x01(\bR\visCompleted\x12 \n" +
	"\vorderStatus\x18\x04 \x01(\tR\vorderStatus\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy2X\n" +
	"\x0fTradeBotService\x12E\n" +
	"\x0eTradeBotAction\x12\x16.trade.TradeBotRequest\x1a\x1b.trade.TradeBotRequestReplyB(Z&engines/tradeExecutor/gRPC/proto/tradeb\x06proto3"

var (
	file_gRPC_proto_trade_proto_rawDescOnce sync.Once
	file_gRPC_proto_trade_proto_rawDescData []byte
)

func file_gRPC_proto_trade_proto_rawDescGZIP() []byte {
	file_gRPC_proto_trade_proto_rawDescOnce.Do(func() {
		file_gRPC_proto_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_proto_trade_proto_rawDesc), len(file_gRPC_proto_trade_proto_rawDesc)))
	})
	return file_gRPC_proto_trade_proto_rawDescData
}

var file_gRPC_proto_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_proto_trade_proto_goTypes = []any{
	(*TradeBotRequest)(nil),      // 0: trade.TradeBotRequest
	(*TradeBotRequestReply)(nil), // 1: trade.TradeBotRequestReply
}
var file_gRPC_proto_trade_proto_depIdxs = []int32{
	0, // 0: trade.TradeBotService.TradeBotAction:input_type -> trade.TradeBotRequest
	1, // 1: trade.TradeBotService.TradeBotAction:output_type -> trade.TradeBotRequestReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_proto_trade_proto_init() }
func file_gRPC_proto_trade_proto_init() {
	if File_gRPC_proto_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_proto_trade_proto_rawDesc), len(file_gRPC_proto_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_proto_trade_proto_goTypes,
		DependencyIndexes: file_gRPC_proto_trade_proto_depIdxs,
		MessageInfos:      file_gRPC_proto_trade_proto_msgTypes,
	}.Build()
	File_gRPC_proto_trade_proto = out.File
	file_gRPC_proto_trade_proto_goTypes = nil
	file_gRPC_proto_trade_proto_depIdxs = nil
}
