apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  # FOLLOWING IS LIST OF KEYWORD IS GETTING USED IN THE BACKEND AND ITS ALL SUB-DIR
  PORT: "8000"
  JWT_SECRET: "SnaxQuantum"
  JWT_REFRESH_SECRET: "SnaxQuantum"
  BCRYPT_SALT_ROUNDS: "10"
  EMAIL_USER: "snaxquantum@gamil.com"

  # THIS IS NOT AN GOOD PRACTISE YOU NEDD TO ENCODE EVERY SECRET AND THEN WRITE THE PIPELINE BUT FOR THIS SAKE
  # FOR PROJECT , I AM NOT DOING THAT I WILL LET HANDLE THE ALL THE HEADCHE OF MINE OF ENCRYPTION FOLLOWING IS ANOTHER WAY OF DOINT IT


  #This is another example of it so follow safety rules for first
# data: 
#   PORT: "ENCODED VALUE"
#   JWT_SECRET: "ENCODED VALUE"
#   JWT_REFRESH_SECRET: "ENCODED VALUE"
#   DB_URL: "ENCODED VALUE"
#   BCRYPT_SALT_ROUNDS: "ENCODED VALUE"
#   EMAIL_USER: "ENCODED VALUE"
  